stages:
  - dependencies
  - test
  - build
  - deploy

install_dependencies:
  image: node:14-alpine
  stage: dependencies
  script:
    - npm install
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

test:
  image: node:14-alpine
  stage: test
  script:
    - npm link @angular/cli
    - npm run test
    - npm run lint
    - npm run audit
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

build:
  image: node:14-alpine
  stage: build
  script:
    - npm link @angular/cli
    - npm run build
  artifacts:
    paths:
      - dist/
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

deploy:
  stage: deploy
  script:
    - echo "Deploying the app"
